# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.CharField(max_length=50, verbose_name='message'),
        ),
    ]
