# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/%Y/%m/image.jpg', upload_to='courses/%Y/%m', verbose_name='cover image'),
        ),
    ]
