# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20171016_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='backend', max_length=50, verbose_name='category of the course'),
        ),
    ]
