# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-19 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_length',
            field=models.IntegerField(default=0, verbose_name='length of the video'),
        ),
    ]
