# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-19 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_teacher_img'),
        ('courses', '0007_video_video_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='goal',
            field=models.CharField(default='', max_length=50, verbose_name='goal of the course'),
        ),
        migrations.AddField(
            model_name='course',
            name='prequist',
            field=models.CharField(default='', max_length=50, verbose_name='preqrust for the course'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='course related teacher'),
        ),
    ]
