# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20171019_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='whether the course will be in banner'),
        ),
    ]
