# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 15:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title of image')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='banner image')),
                ('url', models.CharField(max_length=100, verbose_name='url of the webpage')),
                ('index', models.IntegerField(default=1000, verbose_name='index of the banner image')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='time of added')),
            ],
            options={
                'verbose_name': 'banner images',
                'verbose_name_plural': 'banner images',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='verification code')),
                ('email', models.EmailField(max_length=50, verbose_name='email adderess')),
                ('send_type', models.CharField(choices=[('register', 'registration'), ('forget', 'forget it')], max_length=50)),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'email verification code',
                'verbose_name_plural': 'email verification code',
            },
        ),
    ]
