# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-11 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', 'registration'), ('forget', 'forget it')], max_length=50, verbose_name='verification code type'),
        ),
    ]
