# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 02:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizition',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='time of organization added'),
        ),
        migrations.AddField(
            model_name='organizition',
            name='category',
            field=models.CharField(choices=[('Education Organization', 'training org'), ('Individual', 'person'), ('College', 'higher education')], default='Individual', max_length=50, verbose_name='Org type'),
        ),
        migrations.AddField(
            model_name='organizition',
            name='img',
            field=models.ImageField(default='organizations/%Y/%m/image.jpg', upload_to='organizations/%Y/%m', verbose_name='organization image'),
        ),
    ]
