# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-14 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20171013_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizition',
            name='course_num',
            field=models.IntegerField(default=0, verbose_name='number of courses'),
        ),
        migrations.AddField(
            model_name='organizition',
            name='student_num',
            field=models.IntegerField(default=0, verbose_name='number of students'),
        ),
        migrations.AlterField(
            model_name='organizition',
            name='img',
            field=models.ImageField(default='organizations/%Y/%m/default.jpg', upload_to='organizations/%Y/%m', verbose_name='organization image'),
        ),
    ]
