# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-20 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_teacher_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=23, verbose_name='age of the teacher'),
        ),
    ]
